### PR TITLE
Upgrade to Lets Encrypt v2 API

### PR DESCRIPTION
**Pull request by sjkp**
Refactoring to move away from ACMESharp to Certes. 
In the process also removed everything related to DNS challenge, as it is probably not used by very many.

### CODE REVIEW

**Comment by ohadschn** [comment]
Isn't the DNS challenge mandatory for wildcard certificates? Seeing as such certs are only supported in v2 it would be a shame to miss out on them...

**Comment by sjkp** [comment]
@ohadschn you are right. I have another project that is specific for DNS based challenges, https://github.com/sjkp/letsencrypt-azure - I feel like if you are into using the site extension, you are probably less technically advanced and just want a simple solution, which is why I decided to remove the DNS capabilities. I'm aware that I need to document how to use letsencrypt-azure better, but that will come soon.

**Comment by sjkp** [comment]
#331

**Comment by ohadschn** [comment]
@sjkp in case the docs aren't ready when I want to port, is this the package I should be using? `LetsEncrypt.Azure.Core.V2`

**Pull request merged**
